// src/dummyData.js

const initialData = [
  {
    major: "시각",
    subject: "시각 캡스톤 디자인",
    year: 2017,
    tool: ["피그마", "포토샵"],
    field: "UI",
    likes: 25,
    registrationDate: "2022-03-15",
  },
  {
    major: "제품",
    subject: "서비스 디자인",
    year: 2018,
    tool: ["일러스트", "블렌더"],
    field: "UX",
    likes: 30,
    registrationDate: "2022-05-20",
  },
  {
    major: "시각",
    subject: "커뮤니케이션 디자인",
    year: 2019,
    tool: ["인디자인", "라이노"],
    field: "BRANDING",
    likes: 18,
    registrationDate: "2022-01-10",
  },
  {
    major: "시각",
    subject: "제품 및 서비스 디자인",
    year: 2020,
    tool: ["스케치", "키샷"],
    field: "ARCHITECTURE",
    likes: 35,
    registrationDate: "2022-07-05",
  },
  {
    major: "시각",
    subject: "시각 캡스톤 디자인",
    year: 2021,
    tool: ["피그마", "포토샵"],
    field: "FURNITURE",
    likes: 28,
    registrationDate: "2022-04-30",
  },
  {
    major: "제품",
    subject: "서비스 디자인",
    year: 2022,
    tool: ["일러스트", "블렌더"],
    field: "UX",
    likes: 40,
    registrationDate: "2022-10-12",
  },
  {
    major: "시각",
    subject: "커뮤니케이션 디자인",
    year: 2023,
    tool: ["인디자인", "라이노"],
    field: "FURNITURE",
    likes: 21,
    registrationDate: "2023-02-18",
  },
  {
    major: "시각",
    subject: "제품 및 서비스 디자인",
    year: 2024,
    tool: ["스케치", "키샷"],
    field: "ARCHITECTURE",
    likes: 33,
    registrationDate: "2023-08-07",
  },
  {
    major: "제품",
    subject: "시각 캡스톤 디자인",
    year: 2017,
    tool: ["피그마", "포토샵"],
    field: "UI",
    likes: 22,
    registrationDate: "2022-08-25",
  },
  {
    major: "제품",
    subject: "서비스 디자인",
    year: 2018,
    tool: ["일러스트", "블렌더"],
    field: "UX",
    likes: 27,
    registrationDate: "2022-06-14",
  },
  {
    major: "시각",
    subject: "커뮤니케이션 디자인",
    year: 2019,
    tool: ["인디자인", "라이노"],
    field: "ENVIRONMENTAL",
    likes: 17,
    registrationDate: "2021-12-02",
  },
  {
    major: "시각",
    subject: "제품 및 서비스 디자인",
    year: 2020,
    tool: ["스케치", "키샷"],
    field: "ARCHITECTURE",
    likes: 38,
    registrationDate: "2022-09-08",
  },
  {
    major: "시각",
    subject: "시각 캡스톤 디자인",
    year: 2021,
    tool: ["피그마", "포토샵"],
    field: "ENVIRONMENTAL",
    likes: 31,
    registrationDate: "2022-11-21",
  },
  {
    major: "제품",
    subject: "서비스 디자인",
    year: 2022,
    tool: ["일러스트", "블렌더"],
    field: "VEHICLE",
    likes: 45,
    registrationDate: "2023-05-16",
  },
  {
    major: "시각",
    subject: "커뮤니케이션 디자인",
    year: 2023,
    tool: ["인디자인", "라이노"],
    field: "BRANDING",
    likes: 20,
    registrationDate: "2023-01-30",
  },
  {
    major: "시각",
    subject: "제품 및 서비스 디자인",
    year: 2024,
    tool: ["스케치", "키샷"],
    field: "ARCHITECTURE",
    likes: 37,
    registrationDate: "2023-09-24",
  },
  {
    major: "시각",
    subject: "시각 캡스톤 디자인",
    year: 2017,
    tool: ["피그마", "포토샵"],
    field: "UI",
    likes: 25,
    registrationDate: "2022-03-15",
  },
  {
    major: "제품",
    subject: "서비스 디자인",
    year: 2018,
    tool: ["일러스트", "블렌더"],
    field: "UX",
    likes: 30,
    registrationDate: "2022-05-20",
  },
  {
    major: "시각",
    subject: "커뮤니케이션 디자인",
    year: 2019,
    tool: ["인디자인", "라이노"],
    field: "BRANDING",
    likes: 18,
    registrationDate: "2022-01-10",
  },
  {
    major: "시각",
    subject: "제품 및 서비스 디자인",
    year: 2020,
    tool: ["스케치", "키샷"],
    field: "ARCHITECTURE",
    likes: 35,
    registrationDate: "2022-07-05",
  },
  {
    major: "시각",
    subject: "시각 캡스톤 디자인",
    year: 2021,
    tool: ["피그마", "포토샵"],
    field: "FURNITURE",
    likes: 28,
    registrationDate: "2022-04-30",
  },
  {
    major: "제품",
    subject: "서비스 디자인",
    year: 2022,
    tool: ["일러스트", "블렌더"],
    field: "UX",
    likes: 40,
    registrationDate: "2022-10-12",
  },
  {
    major: "시각",
    subject: "커뮤니케이션 디자인",
    year: 2023,
    tool: ["인디자인", "라이노"],
    field: "FURNITURE",
    likes: 21,
    registrationDate: "2023-02-18",
  },
  {
    major: "시각",
    subject: "제품 및 서비스 디자인",
    year: 2024,
    tool: ["스케치", "키샷"],
    field: "ARCHITECTURE",
    likes: 33,
    registrationDate: "2023-08-07",
  },
  {
    major: "제품",
    subject: "시각 캡스톤 디자인",
    year: 2017,
    tool: ["피그마", "포토샵"],
    field: "UI",
    likes: 22,
    registrationDate: "2022-08-25",
  },
  {
    major: "제품",
    subject: "서비스 디자인",
    year: 2018,
    tool: ["일러스트", "블렌더"],
    field: "UX",
    likes: 27,
    registrationDate: "2022-06-14",
  },
  {
    major: "시각",
    subject: "커뮤니케이션 디자인",
    year: 2019,
    tool: ["인디자인", "라이노"],
    field: "ENVIRONMENTAL",
    likes: 17,
    registrationDate: "2021-12-02",
  },
  {
    major: "시각",
    subject: "제품 및 서비스 디자인",
    year: 2020,
    tool: ["스케치", "키샷"],
    field: "ARCHITECTURE",
    likes: 38,
    registrationDate: "2022-09-08",
  },
  {
    major: "시각",
    subject: "시각 캡스톤 디자인",
    year: 2021,
    tool: ["피그마", "포토샵"],
    field: "ENVIRONMENTAL",
    likes: 31,
    registrationDate: "2022-11-21",
  },
  {
    major: "제품",
    subject: "서비스 디자인",
    year: 2022,
    tool: ["일러스트", "블렌더"],
    field: "VEHICLE",
    likes: 45,
    registrationDate: "2023-05-16",
  },
  {
    major: "시각",
    subject: "커뮤니케이션 디자인",
    year: 2023,
    tool: ["인디자인", "라이노"],
    field: "BRANDING",
    likes: 20,
    registrationDate: "2023-01-30",
  },
  {
    major: "시각",
    subject: "제품 및 서비스 디자인",
    year: 2024,
    tool: ["스케치", "키샷"],
    field: "ARCHITECTURE",
    likes: 37,
    registrationDate: "2023-09-24",
  },
  {
    major: "시각",
    subject: "시각 캡스톤 디자인",
    year: 2017,
    tool: ["피그마", "포토샵"],
    field: "UI",
    likes: 25,
    registrationDate: "2022-03-15",
  },
  {
    major: "제품",
    subject: "서비스 디자인",
    year: 2018,
    tool: ["일러스트", "블렌더"],
    field: "UX",
    likes: 30,
    registrationDate: "2022-05-20",
  },
  {
    major: "시각",
    subject: "커뮤니케이션 디자인",
    year: 2019,
    tool: ["인디자인", "라이노"],
    field: "BRANDING",
    likes: 18,
    registrationDate: "2022-01-10",
  },
  {
    major: "시각",
    subject: "제품 및 서비스 디자인",
    year: 2020,
    tool: ["스케치", "키샷"],
    field: "ARCHITECTURE",
    likes: 35,
    registrationDate: "2022-07-05",
  },
  {
    major: "시각",
    subject: "시각 캡스톤 디자인",
    year: 2021,
    tool: ["피그마", "포토샵"],
    field: "FURNITURE",
    likes: 28,
    registrationDate: "2022-04-30",
  },
  {
    major: "제품",
    subject: "서비스 디자인",
    year: 2022,
    tool: ["일러스트", "블렌더"],
    field: "UX",
    likes: 40,
    registrationDate: "2022-10-12",
  },
  {
    major: "시각",
    subject: "커뮤니케이션 디자인",
    year: 2023,
    tool: ["인디자인", "라이노"],
    field: "FURNITURE",
    likes: 21,
    registrationDate: "2023-02-18",
  },
  {
    major: "시각",
    subject: "제품 및 서비스 디자인",
    year: 2024,
    tool: ["스케치", "키샷"],
    field: "ARCHITECTURE",
    likes: 33,
    registrationDate: "2023-08-07",
  },
  {
    major: "제품",
    subject: "시각 캡스톤 디자인",
    year: 2017,
    tool: ["피그마", "포토샵"],
    field: "UI",
    likes: 22,
    registrationDate: "2022-08-25",
  },
  {
    major: "제품",
    subject: "서비스 디자인",
    year: 2018,
    tool: ["일러스트", "블렌더"],
    field: "UX",
    likes: 27,
    registrationDate: "2022-06-14",
  },
  {
    major: "시각",
    subject: "커뮤니케이션 디자인",
    year: 2019,
    tool: ["인디자인", "라이노"],
    field: "ENVIRONMENTAL",
    likes: 17,
    registrationDate: "2021-12-02",
  },
  {
    major: "시각",
    subject: "제품 및 서비스 디자인",
    year: 2020,
    tool: ["스케치", "키샷"],
    field: "ARCHITECTURE",
    likes: 38,
    registrationDate: "2022-09-08",
  },
  {
    major: "시각",
    subject: "시각 캡스톤 디자인",
    year: 2021,
    tool: ["피그마", "포토샵"],
    field: "ENVIRONMENTAL",
    likes: 31,
    registrationDate: "2022-11-21",
  },
  {
    major: "제품",
    subject: "서비스 디자인",
    year: 2022,
    tool: ["일러스트", "블렌더"],
    field: "VEHICLE",
    likes: 45,
    registrationDate: "2023-05-16",
  },
  {
    major: "시각",
    subject: "커뮤니케이션 디자인",
    year: 2023,
    tool: ["인디자인", "라이노"],
    field: "BRANDING",
    likes: 20,
    registrationDate: "2023-01-30",
  },
  {
    major: "시각",
    subject: "제품 및 서비스 디자인",
    year: 2024,
    tool: ["스케치", "키샷"],
    field: "ARCHITECTURE",
    likes: 37,
    registrationDate: "2023-09-24",
  },
  {
    major: "시각",
    subject: "시각 캡스톤 디자인",
    year: 2017,
    tool: ["피그마", "포토샵"],
    field: "UI",
    likes: 25,
    registrationDate: "2022-03-15",
  },
  {
    major: "제품",
    subject: "서비스 디자인",
    year: 2018,
    tool: ["일러스트", "블렌더"],
    field: "UX",
    likes: 30,
    registrationDate: "2022-05-20",
  },
  {
    major: "시각",
    subject: "커뮤니케이션 디자인",
    year: 2019,
    tool: ["인디자인", "라이노"],
    field: "BRANDING",
    likes: 18,
    registrationDate: "2022-01-10",
  },
  {
    major: "시각",
    subject: "제품 및 서비스 디자인",
    year: 2020,
    tool: ["스케치", "키샷"],
    field: "ARCHITECTURE",
    likes: 35,
    registrationDate: "2022-07-05",
  },
  {
    major: "시각",
    subject: "시각 캡스톤 디자인",
    year: 2021,
    tool: ["피그마", "포토샵"],
    field: "FURNITURE",
    likes: 28,
    registrationDate: "2022-04-30",
  },
  {
    major: "제품",
    subject: "서비스 디자인",
    year: 2022,
    tool: ["일러스트", "블렌더"],
    field: "UX",
    likes: 40,
    registrationDate: "2022-10-12",
  },
  {
    major: "시각",
    subject: "커뮤니케이션 디자인",
    year: 2023,
    tool: ["인디자인", "라이노"],
    field: "FURNITURE",
    likes: 21,
    registrationDate: "2023-02-18",
  },
  {
    major: "시각",
    subject: "제품 및 서비스 디자인",
    year: 2024,
    tool: ["스케치", "키샷"],
    field: "ARCHITECTURE",
    likes: 33,
    registrationDate: "2023-08-07",
  },
  {
    major: "제품",
    subject: "시각 캡스톤 디자인",
    year: 2017,
    tool: ["피그마", "포토샵"],
    field: "UI",
    likes: 22,
    registrationDate: "2022-08-25",
  },
  {
    major: "제품",
    subject: "서비스 디자인",
    year: 2018,
    tool: ["일러스트", "블렌더"],
    field: "UX",
    likes: 27,
    registrationDate: "2022-06-14",
  },
  {
    major: "시각",
    subject: "커뮤니케이션 디자인",
    year: 2019,
    tool: ["인디자인", "라이노"],
    field: "ENVIRONMENTAL",
    likes: 17,
    registrationDate: "2021-12-02",
  },
  {
    major: "시각",
    subject: "제품 및 서비스 디자인",
    year: 2020,
    tool: ["스케치", "키샷"],
    field: "ARCHITECTURE",
    likes: 38,
    registrationDate: "2022-09-08",
  },
  {
    major: "시각",
    subject: "시각 캡스톤 디자인",
    year: 2021,
    tool: ["피그마", "포토샵"],
    field: "ENVIRONMENTAL",
    likes: 31,
    registrationDate: "2022-11-21",
  },
  {
    major: "제품",
    subject: "서비스 디자인",
    year: 2022,
    tool: ["일러스트", "블렌더"],
    field: "VEHICLE",
    likes: 45,
    registrationDate: "2023-05-16",
  },
  {
    major: "시각",
    subject: "커뮤니케이션 디자인",
    year: 2023,
    tool: ["인디자인", "라이노"],
    field: "BRANDING",
    likes: 20,
    registrationDate: "2023-01-30",
  },
  {
    major: "시각",
    subject: "제품 및 서비스 디자인",
    year: 2024,
    tool: ["스케치", "키샷"],
    field: "ARCHITECTURE",
    likes: 37,
    registrationDate: "2023-09-24",
  },
  {
    major: "시각",
    subject: "시각 캡스톤 디자인",
    year: 2017,
    tool: ["피그마", "포토샵"],
    field: "UI",
    likes: 25,
    registrationDate: "2022-03-15",
  },
  {
    major: "제품",
    subject: "서비스 디자인",
    year: 2018,
    tool: ["일러스트", "블렌더"],
    field: "UX",
    likes: 30,
    registrationDate: "2022-05-20",
  },
  {
    major: "시각",
    subject: "커뮤니케이션 디자인",
    year: 2019,
    tool: ["인디자인", "라이노"],
    field: "BRANDING",
    likes: 18,
    registrationDate: "2022-01-10",
  },
  {
    major: "시각",
    subject: "제품 및 서비스 디자인",
    year: 2020,
    tool: ["스케치", "키샷"],
    field: "ARCHITECTURE",
    likes: 35,
    registrationDate: "2022-07-05",
  },
  {
    major: "시각",
    subject: "시각 캡스톤 디자인",
    year: 2021,
    tool: ["피그마", "포토샵"],
    field: "FURNITURE",
    likes: 28,
    registrationDate: "2022-04-30",
  },
  {
    major: "제품",
    subject: "서비스 디자인",
    year: 2022,
    tool: ["일러스트", "블렌더"],
    field: "UX",
    likes: 40,
    registrationDate: "2022-10-12",
  },
  {
    major: "시각",
    subject: "커뮤니케이션 디자인",
    year: 2023,
    tool: ["인디자인", "라이노"],
    field: "FURNITURE",
    likes: 21,
    registrationDate: "2023-02-18",
  },
  {
    major: "시각",
    subject: "제품 및 서비스 디자인",
    year: 2024,
    tool: ["스케치", "키샷"],
    field: "ARCHITECTURE",
    likes: 33,
    registrationDate: "2023-08-07",
  },
  {
    major: "제품",
    subject: "시각 캡스톤 디자인",
    year: 2017,
    tool: ["피그마", "포토샵"],
    field: "UI",
    likes: 22,
    registrationDate: "2022-08-25",
  },
  {
    major: "제품",
    subject: "서비스 디자인",
    year: 2018,
    tool: ["일러스트", "블렌더"],
    field: "UX",
    likes: 27,
    registrationDate: "2022-06-14",
  },
  {
    major: "시각",
    subject: "커뮤니케이션 디자인",
    year: 2019,
    tool: ["인디자인", "라이노"],
    field: "ENVIRONMENTAL",
    likes: 17,
    registrationDate: "2021-12-02",
  },
  {
    major: "시각",
    subject: "제품 및 서비스 디자인",
    year: 2020,
    tool: ["스케치", "키샷"],
    field: "ARCHITECTURE",
    likes: 38,
    registrationDate: "2022-09-08",
  },
  {
    major: "시각",
    subject: "시각 캡스톤 디자인",
    year: 2021,
    tool: ["피그마", "포토샵"],
    field: "ENVIRONMENTAL",
    likes: 31,
    registrationDate: "2022-11-21",
  },
  {
    major: "제품",
    subject: "서비스 디자인",
    year: 2022,
    tool: ["일러스트", "블렌더"],
    field: "VEHICLE",
    likes: 45,
    registrationDate: "2023-05-16",
  },
  {
    major: "시각",
    subject: "커뮤니케이션 디자인",
    year: 2023,
    tool: ["인디자인", "라이노"],
    field: "BRANDING",
    likes: 20,
    registrationDate: "2023-01-30",
  },
  {
    major: "시각",
    subject: "제품 및 서비스 디자인",
    year: 2024,
    tool: ["스케치", "키샷"],
    field: "ARCHITECTURE",
    likes: 37,
    registrationDate: "2023-09-24",
  },
  {
    major: "시각",
    subject: "제품 및 서비스 디자인",
    year: 2020,
    tool: ["스케치", "키샷"],
    field: "ARCHITECTURE",
    likes: 38,
    registrationDate: "2022-09-08",
  },
  {
    major: "시각",
    subject: "시각 캡스톤 디자인",
    year: 2021,
    tool: ["피그마", "포토샵"],
    field: "ENVIRONMENTAL",
    likes: 31,
    registrationDate: "2022-11-21",
  },
  {
    major: "제품",
    subject: "서비스 디자인",
    year: 2022,
    tool: ["일러스트", "블렌더"],
    field: "VEHICLE",
    likes: 45,
    registrationDate: "2023-05-16",
  },
  {
    major: "시각",
    subject: "커뮤니케이션 디자인",
    year: 2023,
    tool: ["인디자인", "라이노"],
    field: "BRANDING",
    likes: 20,
    registrationDate: "2023-01-30",
  },
  {
    major: "시각",
    subject: "제품 및 서비스 디자인",
    year: 2024,
    tool: ["스케치", "키샷"],
    field: "ARCHITECTURE",
    likes: 37,
    registrationDate: "2023-09-24",
  },
  {
    major: "시각",
    subject: "시각 캡스톤 디자인",
    year: 2017,
    tool: ["피그마", "포토샵"],
    field: "UI",
    likes: 25,
    registrationDate: "2022-03-15",
  },
  {
    major: "제품",
    subject: "서비스 디자인",
    year: 2018,
    tool: ["일러스트", "블렌더"],
    field: "UX",
    likes: 30,
    registrationDate: "2022-05-20",
  },
  {
    major: "시각",
    subject: "커뮤니케이션 디자인",
    year: 2019,
    tool: ["인디자인", "라이노"],
    field: "BRANDING",
    likes: 18,
    registrationDate: "2022-01-10",
  },
  {
    major: "시각",
    subject: "제품 및 서비스 디자인",
    year: 2020,
    tool: ["스케치", "키샷"],
    field: "ARCHITECTURE",
    likes: 35,
    registrationDate: "2022-07-05",
  },
  {
    major: "시각",
    subject: "시각 캡스톤 디자인",
    year: 2021,
    tool: ["피그마", "포토샵"],
    field: "FURNITURE",
    likes: 28,
    registrationDate: "2022-04-30",
  },
  {
    major: "제품",
    subject: "서비스 디자인",
    year: 2022,
    tool: ["일러스트", "블렌더"],
    field: "UX",
    likes: 40,
    registrationDate: "2022-10-12",
  },
  {
    major: "시각",
    subject: "커뮤니케이션 디자인",
    year: 2023,
    tool: ["인디자인", "라이노"],
    field: "FURNITURE",
    likes: 21,
    registrationDate: "2023-02-18",
  },
  {
    major: "시각",
    subject: "제품 및 서비스 디자인",
    year: 2024,
    tool: ["스케치", "키샷"],
    field: "ARCHITECTURE",
    likes: 33,
    registrationDate: "2023-08-07",
  },
  {
    major: "제품",
    subject: "시각 캡스톤 디자인",
    year: 2017,
    tool: ["피그마", "포토샵"],
    field: "UI",
    likes: 22,
    registrationDate: "2022-08-25",
  },
  {
    major: "제품",
    subject: "서비스 디자인",
    year: 2018,
    tool: ["일러스트", "블렌더"],
    field: "UX",
    likes: 27,
    registrationDate: "2022-06-14",
  },
  {
    major: "시각",
    subject: "커뮤니케이션 디자인",
    year: 2019,
    tool: ["인디자인", "라이노"],
    field: "ENVIRONMENTAL",
    likes: 17,
    registrationDate: "2021-12-02",
  },
  {
    major: "시각",
    subject: "제품 및 서비스 디자인",
    year: 2020,
    tool: ["스케치", "키샷"],
    field: "ARCHITECTURE",
    likes: 38,
    registrationDate: "2022-09-08",
  },
  {
    major: "시각",
    subject: "시각 캡스톤 디자인",
    year: 2021,
    tool: ["피그마", "포토샵"],
    field: "ENVIRONMENTAL",
    likes: 31,
    registrationDate: "2022-11-21",
  },
  {
    major: "제품",
    subject: "서비스 디자인",
    year: 2022,
    tool: ["일러스트", "블렌더"],
    field: "VEHICLE",
    likes: 45,
    registrationDate: "2023-05-16",
  },
  {
    major: "시각",
    subject: "커뮤니케이션 디자인",
    year: 2023,
    tool: ["인디자인", "라이노"],
    field: "BRANDING",
    likes: 20,
    registrationDate: "2023-01-30",
  },
  {
    major: "시각",
    subject: "제품 및 서비스 디자인",
    year: 2024,
    tool: ["스케치", "키샷"],
    field: "ARCHITECTURE",
    likes: 37,
    registrationDate: "2023-09-24",
  },
  {
    major: "시각",
    subject: "시각 캡스톤 디자인",
    year: 2017,
    tool: ["피그마", "포토샵"],
    field: "UI",
    likes: 25,
    registrationDate: "2022-03-15",
  },
  {
    major: "제품",
    subject: "서비스 디자인",
    year: 2018,
    tool: ["일러스트", "블렌더"],
    field: "UX",
    likes: 30,
    registrationDate: "2022-05-20",
  },
  {
    major: "시각",
    subject: "커뮤니케이션 디자인",
    year: 2019,
    tool: ["인디자인", "라이노"],
    field: "BRANDING",
    likes: 18,
    registrationDate: "2022-01-10",
  },
  {
    major: "시각",
    subject: "제품 및 서비스 디자인",
    year: 2020,
    tool: ["스케치", "키샷"],
    field: "ARCHITECTURE",
    likes: 35,
    registrationDate: "2022-07-05",
  },
  {
    major: "시각",
    subject: "시각 캡스톤 디자인",
    year: 2021,
    tool: ["피그마", "포토샵"],
    field: "FURNITURE",
    likes: 28,
    registrationDate: "2022-04-30",
  },
  {
    major: "제품",
    subject: "서비스 디자인",
    year: 2022,
    tool: ["일러스트", "블렌더"],
    field: "UX",
    likes: 40,
    registrationDate: "2022-10-12",
  },
  {
    major: "시각",
    subject: "커뮤니케이션 디자인",
    year: 2023,
    tool: ["인디자인", "라이노"],
    field: "FURNITURE",
    likes: 21,
    registrationDate: "2023-02-18",
  },
  {
    major: "시각",
    subject: "제품 및 서비스 디자인",
    year: 2024,
    tool: ["스케치", "키샷"],
    field: "ARCHITECTURE",
    likes: 33,
    registrationDate: "2023-08-07",
  },
  {
    major: "제품",
    subject: "시각 캡스톤 디자인",
    year: 2017,
    tool: ["피그마", "포토샵"],
    field: "UI",
    likes: 22,
    registrationDate: "2022-08-25",
  },
  {
    major: "제품",
    subject: "서비스 디자인",
    year: 2018,
    tool: ["일러스트", "블렌더"],
    field: "UX",
    likes: 27,
    registrationDate: "2022-06-14",
  },
  {
    major: "시각",
    subject: "커뮤니케이션 디자인",
    year: 2019,
    tool: ["인디자인", "라이노"],
    field: "ENVIRONMENTAL",
    likes: 17,
    registrationDate: "2021-12-02",
  },
  {
    major: "시각",
    subject: "제품 및 서비스 디자인",
    year: 2020,
    tool: ["스케치", "키샷"],
    field: "ARCHITECTURE",
    likes: 38,
    registrationDate: "2022-09-08",
  },
  {
    major: "시각",
    subject: "시각 캡스톤 디자인",
    year: 2021,
    tool: ["피그마", "포토샵"],
    field: "ENVIRONMENTAL",
    likes: 31,
    registrationDate: "2022-11-21",
  },
  {
    major: "제품",
    subject: "서비스 디자인",
    year: 2022,
    tool: ["일러스트", "블렌더"],
    field: "VEHICLE",
    likes: 45,
    registrationDate: "2023-05-16",
  },
  {
    major: "시각",
    subject: "커뮤니케이션 디자인",
    year: 2023,
    tool: ["인디자인", "라이노"],
    field: "BRANDING",
    likes: 20,
    registrationDate: "2023-01-30",
  },
  {
    major: "시각",
    subject: "제품 및 서비스 디자인",
    year: 2024,
    tool: ["스케치", "키샷"],
    field: "ARCHITECTURE",
    likes: 37,
    registrationDate: "2023-09-24",
  },
  {
    major: "시각",
    subject: "제품 및 서비스 디자인",
    year: 2020,
    tool: ["스케치", "키샷"],
    field: "ARCHITECTURE",
    likes: 38,
    registrationDate: "2022-09-08",
  },
  {
    major: "시각",
    subject: "시각 캡스톤 디자인",
    year: 2021,
    tool: ["피그마", "포토샵"],
    field: "ENVIRONMENTAL",
    likes: 31,
    registrationDate: "2022-11-21",
  },
  {
    major: "제품",
    subject: "서비스 디자인",
    year: 2022,
    tool: ["일러스트", "블렌더"],
    field: "VEHICLE",
    likes: 45,
    registrationDate: "2023-05-16",
  },
  {
    major: "시각",
    subject: "커뮤니케이션 디자인",
    year: 2023,
    tool: ["인디자인", "라이노"],
    field: "BRANDING",
    likes: 20,
    registrationDate: "2023-01-30",
  },
  {
    major: "시각",
    subject: "제품 및 서비스 디자인",
    year: 2024,
    tool: ["스케치", "키샷"],
    field: "ARCHITECTURE",
    likes: 37,
    registrationDate: "2023-09-24",
  },
  {
    major: "시각",
    subject: "시각 캡스톤 디자인",
    year: 2017,
    tool: ["피그마", "포토샵"],
    field: "UI",
    likes: 25,
    registrationDate: "2022-03-15",
  },
  {
    major: "제품",
    subject: "서비스 디자인",
    year: 2018,
    tool: ["일러스트", "블렌더"],
    field: "UX",
    likes: 30,
    registrationDate: "2022-05-20",
  },
  {
    major: "시각",
    subject: "커뮤니케이션 디자인",
    year: 2019,
    tool: ["인디자인", "라이노"],
    field: "BRANDING",
    likes: 18,
    registrationDate: "2022-01-10",
  },
  {
    major: "시각",
    subject: "제품 및 서비스 디자인",
    year: 2020,
    tool: ["스케치", "키샷"],
    field: "ARCHITECTURE",
    likes: 35,
    registrationDate: "2022-07-05",
  },
  {
    major: "시각",
    subject: "시각 캡스톤 디자인",
    year: 2021,
    tool: ["피그마", "포토샵"],
    field: "FURNITURE",
    likes: 28,
    registrationDate: "2022-04-30",
  },
  {
    major: "제품",
    subject: "서비스 디자인",
    year: 2022,
    tool: ["일러스트", "블렌더"],
    field: "UX",
    likes: 40,
    registrationDate: "2022-10-12",
  },
  {
    major: "시각",
    subject: "커뮤니케이션 디자인",
    year: 2023,
    tool: ["인디자인", "라이노"],
    field: "FURNITURE",
    likes: 21,
    registrationDate: "2023-02-18",
  },
  {
    major: "시각",
    subject: "제품 및 서비스 디자인",
    year: 2024,
    tool: ["스케치", "키샷"],
    field: "ARCHITECTURE",
    likes: 33,
    registrationDate: "2023-08-07",
  },
  {
    major: "제품",
    subject: "시각 캡스톤 디자인",
    year: 2017,
    tool: ["피그마", "포토샵"],
    field: "UI",
    likes: 22,
    registrationDate: "2022-08-25",
  },
  {
    major: "제품",
    subject: "서비스 디자인",
    year: 2018,
    tool: ["일러스트", "블렌더"],
    field: "UX",
    likes: 27,
    registrationDate: "2022-06-14",
  },
  {
    major: "시각",
    subject: "커뮤니케이션 디자인",
    year: 2019,
    tool: ["인디자인", "라이노"],
    field: "ENVIRONMENTAL",
    likes: 17,
    registrationDate: "2021-12-02",
  },
  {
    major: "시각",
    subject: "제품 및 서비스 디자인",
    year: 2020,
    tool: ["스케치", "키샷"],
    field: "ARCHITECTURE",
    likes: 38,
    registrationDate: "2022-09-08",
  },
  {
    major: "시각",
    subject: "시각 캡스톤 디자인",
    year: 2021,
    tool: ["피그마", "포토샵"],
    field: "ENVIRONMENTAL",
    likes: 31,
    registrationDate: "2022-11-21",
  },
  {
    major: "제품",
    subject: "서비스 디자인",
    year: 2022,
    tool: ["일러스트", "블렌더"],
    field: "VEHICLE",
    likes: 45,
    registrationDate: "2023-05-16",
  },
  {
    major: "시각",
    subject: "커뮤니케이션 디자인",
    year: 2023,
    tool: ["인디자인", "라이노"],
    field: "BRANDING",
    likes: 20,
    registrationDate: "2023-01-30",
  },
  {
    major: "시각",
    subject: "제품 및 서비스 디자인",
    year: 2024,
    tool: ["스케치", "키샷"],
    field: "ARCHITECTURE",
    likes: 37,
    registrationDate: "2023-09-24",
  },
  {
    major: "시각",
    subject: "시각 캡스톤 디자인",
    year: 2017,
    tool: ["피그마", "포토샵"],
    field: "UI",
    likes: 25,
    registrationDate: "2022-03-15",
  },
  {
    major: "제품",
    subject: "서비스 디자인",
    year: 2018,
    tool: ["일러스트", "블렌더"],
    field: "UX",
    likes: 30,
    registrationDate: "2022-05-20",
  },
  {
    major: "시각",
    subject: "커뮤니케이션 디자인",
    year: 2019,
    tool: ["인디자인", "라이노"],
    field: "BRANDING",
    likes: 18,
    registrationDate: "2022-01-10",
  },
  {
    major: "시각",
    subject: "제품 및 서비스 디자인",
    year: 2020,
    tool: ["스케치", "키샷"],
    field: "ARCHITECTURE",
    likes: 35,
    registrationDate: "2022-07-05",
  },
  {
    major: "시각",
    subject: "시각 캡스톤 디자인",
    year: 2021,
    tool: ["피그마", "포토샵"],
    field: "FURNITURE",
    likes: 28,
    registrationDate: "2022-04-30",
  },
  {
    major: "제품",
    subject: "서비스 디자인",
    year: 2022,
    tool: ["일러스트", "블렌더"],
    field: "UX",
    likes: 40,
    registrationDate: "2022-10-12",
  },
  {
    major: "시각",
    subject: "커뮤니케이션 디자인",
    year: 2023,
    tool: ["인디자인", "라이노"],
    field: "FURNITURE",
    likes: 21,
    registrationDate: "2023-02-18",
  },
  {
    major: "시각",
    subject: "제품 및 서비스 디자인",
    year: 2024,
    tool: ["스케치", "키샷"],
    field: "ARCHITECTURE",
    likes: 33,
    registrationDate: "2023-08-07",
  },
  {
    major: "제품",
    subject: "시각 캡스톤 디자인",
    year: 2017,
    tool: ["피그마", "포토샵"],
    field: "UI",
    likes: 22,
    registrationDate: "2022-08-25",
  },
  {
    major: "제품",
    subject: "서비스 디자인",
    year: 2018,
    tool: ["일러스트", "블렌더"],
    field: "UX",
    likes: 27,
    registrationDate: "2022-06-14",
  },
  {
    major: "시각",
    subject: "커뮤니케이션 디자인",
    year: 2019,
    tool: ["인디자인", "라이노"],
    field: "ENVIRONMENTAL",
    likes: 17,
    registrationDate: "2021-12-02",
  },
  {
    major: "시각",
    subject: "제품 및 서비스 디자인",
    year: 2020,
    tool: ["스케치", "키샷"],
    field: "ARCHITECTURE",
    likes: 38,
    registrationDate: "2022-09-08",
  },
  {
    major: "시각",
    subject: "시각 캡스톤 디자인",
    year: 2021,
    tool: ["피그마", "포토샵"],
    field: "ENVIRONMENTAL",
    likes: 31,
    registrationDate: "2022-11-21",
  },
  {
    major: "제품",
    subject: "서비스 디자인",
    year: 2022,
    tool: ["일러스트", "블렌더"],
    field: "VEHICLE",
    likes: 45,
    registrationDate: "2023-05-16",
  },
  {
    major: "시각",
    subject: "커뮤니케이션 디자인",
    year: 2023,
    tool: ["인디자인", "라이노"],
    field: "BRANDING",
    likes: 20,
    registrationDate: "2023-01-30",
  },
  {
    major: "시각",
    subject: "제품 및 서비스 디자인",
    year: 2024,
    tool: ["스케치", "키샷"],
    field: "ARCHITECTURE",
    likes: 37,
    registrationDate: "2023-09-24",
  },
];

export default initialData;
